# Generated by Django 2.1.5 on 2019-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='gambar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
