# Generated by Django 2.1.5 on 2019-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_mentee_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='nilai_rata_rata',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='nomor_absen',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='nomor_telepon',
        ),
        migrations.AddField(
            model_name='mentee',
            name='status',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
