# Generated by Django 2.1.5 on 2019-02-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20190212_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='gambar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
