# Generated by Django 2.1.5 on 2019-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190212_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gambar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
