# Generated by Django 2.1.5 on 2019-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190212_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gambar',
            field=models.ImageField(upload_to='media'),
        ),
    ]
