# Generated by Django 2.1.5 on 2019-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.IntegerField()),
                ('mata_pelajaran', models.TextField(max_length=255)),
            ],
        ),
    ]
