# Generated by Django 2.1.5 on 2019-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='mata_pelajaran',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='nomor_telepon',
        ),
        migrations.AddField(
            model_name='mentor',
            name='gambar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
