# Generated by Django 2.1.5 on 2019-02-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20190212_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='gambar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
